const ACCOUNT = {
  FETCH: "ACCOUNT_FETCH",
  FETCH_ERROR: "ACCOUNT_FETCH_ERROR",
  FETCH_SUCCESS: "ACCOUNT_FETCH_SUCCESS",
  FETCH_LOGOUT_SUCCESS: "ACCOUNT_FETCH_LOGOUT_SUCCESS",
  FETCH_AUTHENTICATED_SUCCESS: "ACCOUNT_FETCH_AUTHENTICATED_SUCCESS",
};

const EMPLOYEE = {
  FETCH: "EMPLOYEE_FETCH",
  FETCH_ERROR: "EMPLOYEE_FETCH_ERROR",
  FETCH_SUCCESS: "EMPLOYEE_FETCH_SUCCESS",
  GET: "EMPLOYEE_GET",
  ADD: "EMPLOYEE_ADD",
  ADD_ERROR: "EMPLOYEE_ADD_ERROR",
  ADD_FETCH: "EMPLOYEE_ADD_FETCH",
  UPDATE: "EMPLOYEE_UPDATE",
  ERROR: "EMPLOYEE_ERROR",
};

const DETACHMENT = {
  FETCH: "DETACHMENT_FETCH",
  FETCH_ERROR: "DETACHMENT_FETCH_ERROR",
  FETCH_SUCCESS: "DETACHMENT_FETCH_SUCCESS",
  GET: "DETACHMENT_GET",
  GET_EMPLOYEE: "DETACHMENT_GET_EMPLOYEE",
  ADD: "DETACHMENT_ADD",
  ADD_ERROR: "DETACHMENT_ADD_ERROR",
  ADD_FETCH: "DETACHMENT_ADD_FETCH",
  UPDATE: "DETACHMENT_UPDATE",
  ERROR: "DETACHMENT_ERROR",
};

export { ACCOUNT, EMPLOYEE, DETACHMENT };
