const ACCOUNT = {
  FETCH: "ACCOUNT_FETCH",
  FETCH_ERROR: "ACCOUNT_FETCH_ERROR",
  FETCH_SUCCESS: "ACCOUNT_FETCH_SUCCESS",
  FETCH_LOGOUT_SUCCESS: "ACCOUNT_FETCH_LOGOUT_SUCCESS",
  FETCH_AUTHENTICATED_SUCCESS: "ACCOUNT_FETCH_AUTHENTICATED_SUCCESS",
};

const EMPLOYEE = {
  FETCH: "EMPLOYEE_FETCH",
  FETCH_ERROR: "EMPLOYEE_FETCH_ERROR",
  FETCH_SUCCESS: "EMPLOYEE_FETCH_SUCCESS",
  GET: "EMPLOYEE_GET",
  ADD: "EMPLOYEE_ADD",
  ADD_ERROR: "EMPLOYEE_ADD_ERROR",
  ADD_FETCH: "EMPLOYEE_ADD_FETCH",
  UPDATE: "EMPLOYEE_UPDATE",
  ERROR: "EMPLOYEE_ERROR",
};

export { ACCOUNT, EMPLOYEE };
